version: 2
jobs:
  sanity:
    docker:
    - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install --user -r ci/requirements.txt
    - run:
        name: linter
        command: |
          flake8 .
    - run:
        name: install package
        command: |
          pip install --user .
  release:
    docker:
    - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install --user -r ci/requirements.txt
    - run:
        name: generate .pypirc
        command: |
          echo -e "[pypi]" >> ~/.pypirc
          echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
    - run:
        name: build package
        command: |
          python setup.py sdist
    - run:
        name: upload to pypi
        command: |
          twine upload dist/*
workflows:
  version: 2
  sanity:
    jobs:
    - sanity:
        filters:
          branches:
            only: /.*/
          tags:
            ignore: /.*/
  release:
    jobs:
    - sanity:
        filters:
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
          branches:
            ignore: /.*/
    - release:
        filters:
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
          branches:
            ignore: /.*/
        requires:
        - sanity
